#!/usr/bin/env bash
#Custom http response headers

sudo apt-get update
sudo apt-get install nginx

sudo sed -i '/location \/ {/a\ \tadd_header X-served-By $hostname always;' /etc/nginx/sites-available/default
sudo service nginx restart