#!/usr/bin/env bash
#Install HaProxy on LoadBalancer

sudo apt-get update && sudo apt-get install haproxy -y
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

grep -q "frontend balancer_http_in" /etc/haproxy/haproxy.cfg ||
cat <<'EOF' | sudo tee -a /etc/haproxy/haproxy.cfg

frontend balancer_http_in
    bind *:80
    default_backend balancer_http_out

backend balancer_http_out
    balance roundrobin
    server 7172-web-01 10.227.126.233:80 check
    server 7172-web-02 10.227.55.229:80 check 
EOF
sudo service haproxy restart
