#!/usr/bin/env bash
#Install nginx on server

sudo apt update && sudo apt install nginx -y
echo "<html><p>Holberton School</p></html>" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
