#!/usr/bin/env bash
#Redirect server to new domain
file=/etc/nginx/sites-available/
new_line="server_name youtube.com\nreturn 301 youtube.com\$request_uri;\n"

sudo apt update && sudo apt install nginx -y
sudo sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;\n\t}' /etc/nginx/sites-available/default

sudo service nginx restart

